#!/bin/bash

echo "=== 外网访问解决方案 ==="
echo ""
echo "当前状况："
echo "- 外网IP: 67.169.169.65"
echo "- 访问该IP显示其他网站（可能是路由器托管的）"
echo "- 本地nginx运行正常"
echo ""
echo "解决方案："
echo ""
echo "1. 配置路由器端口转发："
echo "   - 登录路由器管理界面"
echo "   - 找到端口转发/虚拟服务器设置"
echo "   - 添加规则："
echo "     外部端口: 8080 (或其他未占用端口)"
echo "     内部IP: 192.168.0.20"
echo "     内部端口: 80"
echo "   - 访问地址: http://67.169.169.65:8080"
echo ""
echo "2. 使用其他端口的nginx配置："
echo "   - 修改nginx监听8080端口"
echo "   - 路由器转发8080到8080"
echo ""
echo "3. 使用内网穿透服务（推荐）："
echo "   - ngrok: 简单易用，提供临时域名"
echo "   - frp: 需要自己的服务器"
echo "   - cloudflare tunnel: 免费且稳定"
echo ""
echo "4. 检查路由器设置："
echo "   - 确认是否有DMZ主机设置"
echo "   - 检查防火墙规则"
echo "   - 查看是否有其他服务占用80端口"